---
title: "07-functions"
author: "Lauren Yamane"
date: "9/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Functions tutorial

## Set up some test data

```{r load_data}
airtemps <- c(212, 78, 3, 30, 32)
celsius1 <- (airtemps[1]-32)*(5/9)
celsius2 <- (airtemps[2]-32)*(5/9)
celsius3 <- (airtemps[3]-32)*(5/9)
celsius4 <- (airtemps[4]-32)*(5/9)
```
```{r create_function}
fahr_to_celsius <- function(fahr){
  celsius <- (fahr-32)*(5/9)
  return(celsius)
}

celsius5 <- fahr_to_celsius(airtemps[1])
celsius5
celsius5 == celsius1
```
```{r}
celsius <- fahr_to_celsius(airtemps)
celsius
```
```{r func_cels_to_fahr}
celsius_to_fahr <- function(celsius){
  celsius*9/5 + 32
}
```
```{r}
airtemps2 <- c(12, 5, 15, 25)
fahr <- celsius_to_fahr(airtemps2)
fahr
```

```{r}
convert_temps <- function(fahr){
  celsius <- (fahr - 32)*(5/9)
  kelvin <- celsius + 273.15
  return(list(fahr=fahr, celsius = celsius, kelvin = kelvin))
}

temps_df <- data.frame(convert_temps(seq(-100, 100, 10)))
temps_df
```
```{r themes_customization}
custom_theme <- function(base_size = 9) {
  ggplot2::theme(
    axis.ticks = ggplot2::element_blank(), 
    text = ggplot2::element_text(family = 'Helvetica', color = 'gray30', size = base_size)
  )
} # base_size = 9 is the default font size value if not specified by user

library(ggplot2)
ggplot(temps_df, mapping = aes(x = fahr, y = celsius, color = kelvin)) + geom_point() + custom_theme(10)
```
```{r}
scatterplot <- function(df, point_size = 2, font_size=9) {
  ggplot(df, mapping=aes(x=fahr, y=celsius, color=kelvin)) +
    geom_point(size=point_size) +
    custom_theme(font_size)
}

scatterplot(temps_df, point_size = 3, font_size = 16)
```
```{r}

```


