---
title: "data_cleaning"
author: "Lauren Yamane"
date: "9/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message = FALSE}
library(dplyr)
library(tidyr)
```
## Data Sources

Read in the data from [KNB](https://knb.ecoinformatics.org/view/df35b.304.2)
```{r}
catch_original <- read.csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
glimpse(catch_original)
```
## Clean and reshape data

* remove unnecessary columns
* check column types
* reshape data

```{r}
catch_data <- catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)

# or select(-All, -notesRegCode)
```

```{r}
catch_clean <- catch_data %>% 
  mutate(Chinook = as.numeric(Chinook))

glimpse(catch_clean)
```
```{r}
i <- which(is.na(catch_clean$Chinook))
i

# show row i of catch_original
catch_original[i, ]
```
```{r}
catch_clean <- catch_data %>%
  mutate(Chinook = if_else(Chinook == "I", "1", Chinook)) %>%
  mutate(Chinook = as.integer(Chinook))

glimpse(catch_clean)
```
reshape data
```{r}
catch_long <- catch_clean %>%
  pivot_longer(cols = -c(Region, Year), names_to = "species", values_to = "catch")
```
```{r}
catch_wide <- catch_long %>%
  pivot_wider(names_from = Region, values_from = catch)
```
```{r}
catch_long <- catch_long %>% 
  rename(catch_thousands = catch) %>%
  mutate(catch = catch_thousands * 1000)

```
group and summarise data

```{r}
mean_region <- catch_long %>%
  group_by(Region) %>%
  summarise(catch_mean = mean(catch))

sum_year <- catch_long %>%
  group_by(Year) %>%
  summarise(catch_sum_yr = sum(catch))
```
## Join to regions definitions
```{r}
region_defs <- read.csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1") %>% 
    select(code, mgmtArea)

head(region_defs)
```
```{r}
catch_joined <- left_join(catch_long, region_defs, by = c("Region"="code"))
```

```{r}
#test for github token
```
